//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class newsletter
    {
        public int id { get; set; }
        public string email { get; set; }
        public System.DateTime datasubscricao { get; set; }
    }
}
